CREATE TABLE CUSTOMER (
        ID_CUSTOMER INT IDENTITY,
        NAME_CUSTOMER VARCHAR(30) NOT NULL,
        CPF_CUSTOMER VARCHAR(14) NOT NULL,
        ID_ADDRESS INT NOT NULL
);


CREATE TABLE ADDRESS (
        ID_ADDRESS INT IDENTITY,
        ADDRESS VARCHAR(50) NOT NULL,
        DISTRICT VARCHAR(30) NOT NULL,
        CITY VARCHAR(30) NOT NULL,
        STATE VARCHAR(2) NOT NULL,
        ZIP_CODE VARCHAR(8) NOT NULL,
);